export const players = [
    {
        caseName: "basic player test case with 1 time slot as string",
        playerData: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player1',
            riotId: 'player#001',
            pronouns: 'she/her',
            timeSlots: '7pm CEST/8pm WEST',
            multipleGames: 'yes',
            willSub: 'yes',
            willHost: 'yes',
            duoRequest: 'Player2',
            currentRank: 'Bronze 1',
            peakRank: 'Silver 1',
        },
        expectedData: {
            isValid: true,
            avgRank: 15,
            multipleGames: true,
            willSub: true,
            willHost: true,
            timeSlots: ['7pm CEST/8pm WEST'],
            currentRank: 10,
            peakRank: 20,
        }
    },
    {
        caseName: "basic player test case with 2 time slots as string",
        playerData: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player1',
            riotId: 'player#001',
            pronouns: 'she/her',
            timeSlots: '7pm CEST/8pm WEST,8pm CEST/9pm WEST',
            multipleGames: 'yes',
            willSub: 'yes',
            willHost: 'yes',
            duoRequest: '',
            currentRank: 'Bronze 1',
            peakRank: 'Silver 1',
        },
        expectedData: {
            isValid: true,
            avgRank: 15,
            multipleGames: true,
            willSub: true,
            willHost: true,
            timeSlots: ['7pm CEST/8pm WEST', '8pm CEST/9pm WEST'],
            currentRank: 10,
            peakRank: 20,
        }
    },
    {
        caseName: "basic player test case with 1 time slot as array",
        playerData: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player1',
            riotId: 'player#001',
            pronouns: 'she/her',
            timeSlots: ['7pm CEST/8pm WEST'],
            multipleGames: 'yes',
            willSub: 'yes',
            willHost: 'yes',
            duoRequest: '',
            currentRank: 'Bronze 1',
            peakRank: 'Silver 1',
        },
        expectedData: {
            isValid: true,
            avgRank: 15,
            multipleGames: true,
            willSub: true,
            willHost: true,
            timeSlots: ['7pm CEST/8pm WEST'],
            currentRank: 10,
            peakRank: 20,
        }
    },
    {
        caseName: "basic player test case with 2 time slots as array",
        playerData: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player1',
            riotId: 'player#001',
            pronouns: 'she/her',
            timeSlots: ['7pm CEST/8pm WEST','8pm CEST/9pm WEST'],
            multipleGames: 'yes',
            willSub: 'yes',
            willHost: 'yes',
            duoRequest: '',
            currentRank: 'Bronze 1',
            peakRank: 'Silver 1',
        },
        expectedData: {
            isValid: true,
            avgRank: 15,
            multipleGames: true,
            willSub: true,
            willHost: true,
            timeSlots: ['7pm CEST/8pm WEST', '8pm CEST/9pm WEST'],
            currentRank: 10,
            peakRank: 20,
        }
    },
    {
        caseName: "basic player test case with everything false",
        playerData: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player1',
            riotId: 'player#001',
            pronouns: 'she/her',
            timeSlots: ['7pm CEST/8pm WEST'],
            multipleGames: 'no',
            willSub: 'no',
            willHost: 'no',
            duoRequest: '',
            currentRank: 'Ascendant 3',
            peakRank: 'Immortal 2',
        },
        expectedData: {
            isValid: true,
            avgRank: 77.5,
            multipleGames: false,
            willSub: false,
            willHost: false,
            timeSlots: ['7pm CEST/8pm WEST'],
            currentRank: 70,
            peakRank: 85,
        }
    },
    {
        caseName: "invalid player because invalid current rank",
        playerData: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player1',
            riotId: 'player#001',
            pronouns: 'she/her',
            timeSlots: ['7pm CEST/8pm WEST'],
            multipleGames: 'no',
            willSub: 'no',
            willHost: 'no',
            duoRequest: '',
            currentRank: '',
            peakRank: 'Immortal 2',
        },
        expectedData: {
            isValid: false,
            avgRank: 42.5 ,
            multipleGames: false,
            willSub: false,
            willHost: false,
            timeSlots: ['7pm CEST/8pm WEST'],
            currentRank: 0,
            peakRank: 85,
        }
    },
    {
        caseName: "invalid player because invalid peak rank",
        playerData: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player1',
            riotId: 'player#001',
            pronouns: 'she/her',
            timeSlots: ['7pm CEST/8pm WEST'],
            multipleGames: 'no',
            willSub: 'no',
            willHost: 'no',
            duoRequest: '',
            currentRank: 'Immortal 2',
            peakRank: '',
        },
        expectedData: {
            isValid: false,
            avgRank: 42.5,
            multipleGames: false,
            willSub: false,
            willHost: false,
            timeSlots: ['7pm CEST/8pm WEST'],
            currentRank: 85,
            peakRank: 0,
        }
    },
    {
        caseName: "invalid player because discord name too short",
        playerData: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'P',
            riotId: 'player#001',
            pronouns: 'she/her',
            timeSlots: ['7pm CEST/8pm WEST'],
            multipleGames: 'no',
            willSub: 'no',
            willHost: 'no',
            duoRequest: '',
            currentRank: 'Platinum 3',
            peakRank: 'Immortal 2',
        },
        expectedData: {
            isValid: false,
            avgRank: 65,
            multipleGames: false,
            willSub: false,
            willHost: false,
            timeSlots: ['7pm CEST/8pm WEST'],
            currentRank: 45,
            peakRank: 85,
        }
    },
    {
        caseName: "invalid player because discord name too long",
        playerData: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player1asldfasdjfaiehlkajsldicaje',
            riotId: 'player#001',
            pronouns: 'she/her',
            timeSlots: ['7pm CEST/8pm WEST'],
            multipleGames: 'no',
            willSub: 'no',
            willHost: 'no',
            duoRequest: '',
            currentRank: 'Platinum 3',
            peakRank: 'Immortal 2',
        },
        expectedData: {
            isValid: false,
            avgRank: 65,
            multipleGames: false,
            willSub: false,
            willHost: false,
            timeSlots: ['7pm CEST/8pm WEST'],
            currentRank: 45,
            peakRank: 85,
        }
    },
    {
        caseName: "invalid player because riot id malformed",
        playerData: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player1',
            riotId: 'player001',
            pronouns: 'she/her',
            timeSlots: ['7pm CEST/8pm WEST'],
            multipleGames: 'no',
            willSub: 'no',
            willHost: 'no',
            duoRequest: '',
            currentRank: 'Platinum 3',
            peakRank: 'Immortal 2',
        },
        expectedData: {
            isValid: false,
            avgRank: 65,
            multipleGames: false,
            willSub: false,
            willHost: false,
            timeSlots: ['7pm CEST/8pm WEST'],
            currentRank: 45,
            peakRank: 85,
        }
    },
    {
        caseName: "invalid player because riot id name too short",
        playerData: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player1',
            riotId: 'pl#001',
            pronouns: 'she/her',
            timeSlots: ['7pm CEST/8pm WEST'],
            multipleGames: 'no',
            willSub: 'no',
            willHost: 'no',
            duoRequest: '',
            currentRank: 'Platinum 3',
            peakRank: 'Immortal 2',
        },
        expectedData: {
            isValid: false,
            avgRank: 65,
            multipleGames: false,
            willSub: false,
            willHost: false,
            timeSlots: ['7pm CEST/8pm WEST'],
            currentRank: 45,
            peakRank: 85,
        }
    },
    {
        caseName: "invalid player because riot id name too long",
        playerData: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player1',
            riotId: 'asdlfjaiepsodijao#001',
            pronouns: 'she/her',
            timeSlots: ['7pm CEST/8pm WEST'],
            multipleGames: 'no',
            willSub: 'no',
            willHost: 'no',
            duoRequest: '',
            currentRank: 'Platinum 3',
            peakRank: 'Immortal 2',
        },
        expectedData: {
            isValid: false,
            avgRank: 65,
            multipleGames: false,
            willSub: false,
            willHost: false,
            timeSlots: ['7pm CEST/8pm WEST'],
            currentRank: 45,
            peakRank: 85,
        }
    },
    {
        caseName: "invalid player because riot id tagline too short",
        playerData: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player1',
            riotId: 'Player#1',
            pronouns: 'she/her',
            timeSlots: ['7pm CEST/8pm WEST'],
            multipleGames: 'no',
            willSub: 'no',
            willHost: 'no',
            duoRequest: '',
            currentRank: 'Platinum 3',
            peakRank: 'Immortal 2',
        },
        expectedData: {
            isValid: false,
            avgRank: 65,
            multipleGames: false,
            willSub: false,
            willHost: false,
            timeSlots: ['7pm CEST/8pm WEST'],
            currentRank: 45,
            peakRank: 85,
        }
    },
    {
        caseName: "invalid player because riot id tagline too long",
        playerData: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player1',
            riotId: 'Player#000001',
            pronouns: 'she/her',
            timeSlots: ['7pm CEST/8pm WEST'],
            multipleGames: 'no',
            willSub: 'no',
            willHost: 'no',
            duoRequest: '',
            currentRank: 'Platinum 3',
            peakRank: 'Immortal 2',
        },
        expectedData: {
            isValid: false,
            avgRank: 65,
            multipleGames: false,
            willSub: false,
            willHost: false,
            timeSlots: ['7pm CEST/8pm WEST'],
            currentRank: 45,
            peakRank: 85,
        }
    },
    {
        caseName: "invalid player because no timeslots set",
        playerData: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player1',
            riotId: 'Player#000001',
            pronouns: 'she/her',
            timeSlots: '',
            multipleGames: 'no',
            willSub: 'no',
            willHost: 'no',
            duoRequest: '',
            currentRank: 'Platinum 3',
            peakRank: 'Immortal 2',
        },
        expectedData: {
            isValid: false,
            avgRank: 65,
            multipleGames: false,
            willSub: false,
            willHost: false,
            timeSlots: [],
            currentRank: 45,
            peakRank: 85,
        }
    },
]

export const playersToggle = [
    {
        caseName: "basic player test case with 1 time slot as string",
        playerData: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player1',
            riotId: 'player#001',
            pronouns: 'she/her',
            timeSlots: '7pm CEST/8pm WEST',
            multipleGames: 'yes',
            willSub: 'yes',
            willHost: 'yes',
            duoRequest: 'Player2',
            currentRank: 'Bronze 1',
            peakRank: 'Silver 1',
        }
    },
]

export const duoPlayers = [
    {
        caseName: "test matching duos",
        player1data: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player1',
            riotId: 'player#001',
            pronouns: 'she/her',
            timeSlots: '7pm CEST/8pm WEST',
            multipleGames: 'yes',
            willSub: 'yes',
            willHost: 'yes',
            duoRequest: 'Player2',
            currentRank: 'Bronze 1',
            peakRank: 'Silver 1',
        },
        player2data: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player2',
            riotId: 'player#002',
            pronouns: 'she/her',
            timeSlots: '7pm CEST/8pm WEST',
            multipleGames: 'yes',
            willSub: 'yes',
            willHost: 'yes',
            duoRequest: 'Player1',
            currentRank: 'Bronze 1',
            peakRank: 'Silver 1',
        },
        player3data: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player3',
            riotId: 'player#003',
            pronouns: 'she/her',
            timeSlots: '7pm CEST/8pm WEST',
            multipleGames: 'yes',
            willSub: 'yes',
            willHost: 'yes',
            duoRequest: '',
            currentRank: 'Bronze 1',
            peakRank: 'Silver 1',
        },
        expected: {
            matchDuo: true
        }
    },
    {
        caseName: "test player 1 valid duo request but no duo for player 2",
        player1data: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player1',
            riotId: 'player#001',
            pronouns: 'she/her',
            timeSlots: '7pm CEST/8pm WEST',
            multipleGames: 'yes',
            willSub: 'yes',
            willHost: 'yes',
            duoRequest: 'Player2',
            currentRank: 'Bronze 1',
            peakRank: 'Silver 1',
        },
        player2data: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player2',
            riotId: 'player#002',
            pronouns: 'she/her',
            timeSlots: '7pm CEST/8pm WEST',
            multipleGames: 'yes',
            willSub: 'yes',
            willHost: 'yes',
            duoRequest: '',
            currentRank: 'Bronze 1',
            peakRank: 'Silver 1',
        },
        player3data: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player3',
            riotId: 'player#003',
            pronouns: 'she/her',
            timeSlots: '7pm CEST/8pm WEST',
            multipleGames: 'yes',
            willSub: 'yes',
            willHost: 'yes',
            duoRequest: '',
            currentRank: 'Bronze 1',
            peakRank: 'Silver 1',
        },
        expected: {
            matchDuo: false
        }
    },
    {
        caseName: "test player 1 valid duo request but not matching for player 2",
        player1data: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player1',
            riotId: 'player#001',
            pronouns: 'she/her',
            timeSlots: '7pm CEST/8pm WEST',
            multipleGames: 'yes',
            willSub: 'yes',
            willHost: 'yes',
            duoRequest: 'Player2',
            currentRank: 'Bronze 1',
            peakRank: 'Silver 1',
        },
        player2data: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player2',
            riotId: 'player#002',
            pronouns: 'she/her',
            timeSlots: '7pm CEST/8pm WEST',
            multipleGames: 'yes',
            willSub: 'yes',
            willHost: 'yes',
            duoRequest: 'Player3',
            currentRank: 'Bronze 1',
            peakRank: 'Silver 1',
        },
        player3data: {
            timestamp: '2024-11-25 16:00:07',
            discordUsername: 'Player3',
            riotId: 'player#003',
            pronouns: 'she/her',
            timeSlots: '7pm CEST/8pm WEST',
            multipleGames: 'yes',
            willSub: 'yes',
            willHost: 'yes',
            duoRequest: '',
            currentRank: 'Bronze 1',
            peakRank: 'Silver 1',
        },
        expected: {
            matchDuo: false
        }
    },
];
